import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {onRequest} from '../server/studio.mjs';import {normalize,analysis} from '../server/core.mjs';import {verifyAppleToken,b64,now,hash} from '../server/auth.mjs';import {syncNotion} from '../server/notion.mjs';
function db(){const d=new DatabaseSync(':memory:');d.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));return {prepare(sql){return {bind(...args){return {first:async()=>d.prepare(sql).get(...args)||null,all:async()=>({results:d.prepare(sql).all(...args)}),run:async()=>d.prepare(sql).run(...args),_sql:sql,_args:args}},first:async()=>d.prepare(sql).get()||null,all:async()=>({results:d.prepare(sql).all()}),_sql:sql,_args:[]}},async batch(ss){d.exec('BEGIN');try{const results=ss.map(s=>d.prepare(s._sql).run(...s._args));d.exec('COMMIT');return results;}catch(e){d.exec('ROLLBACK');throw e;}}};}
const call=(path,env={},opts={})=>onRequest({request:new Request('https://admin.htw0702.com/api/'+path,opts),env});
const full=DB=>({DB,ADMIN_ORIGIN:'https://admin.htw0702.com',APPLE_CLIENT_ID:'client',APPLE_TEAM_ID:'team',APPLE_KEY_ID:'kid',APPLE_PRIVATE_KEY:'key',APPLE_OWNER_SUB:'owner'});
const entry={kind:'blog',locale:'tw',slug:'hello',title:'Hello',body:'Body',visibility:'private',meta:{}};
test('unconfigured admin fails closed and cannot mutate',async()=>{assert.equal((await call('entries')).status,401);assert.equal((await call('entries',{}, {method:'POST',body:JSON.stringify(entry)})).status,401);assert.equal((await call('health')).status,200);assert.deepEqual(await (await call('health')).json(),{auth:false});});
test('public query never returns private records',async()=>{const DB=db();for(const [id,visibility] of [['1','private'],['2','public']])await DB.prepare('INSERT INTO entries(id,kind,locale,slug,title,body,visibility,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,'blog','tw',id,'x','text',visibility,'2026-09-11').run();const r=await (await call('public?kind=blog&locale=tw',{DB})).json();assert.equal(r.entries.length,1);assert.equal(r.entries[0].id,'2');const injected=await (await call("public?kind=blog%27%20OR%201=1--&locale=tw",{DB})).json();assert.equal(injected.entries.length,0);});
test('CSRF, owner session, optimistic concurrency and unpublish',async()=>{const DB=db(),env=full(DB),token='test-token';await DB.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await hash(token),'owner','csrf',now()+100).run();const headers={Cookie:'__Host-studio='+token,'Content-Type':'application/json',Origin:env.ADMIN_ORIGIN,'X-CSRF-Token':'csrf'};assert.equal((await call('entries',env,{method:'POST',headers:{Cookie:headers.Cookie},body:JSON.stringify(entry)})).status,403);const created=await (await call('entries',env,{method:'POST',headers,body:JSON.stringify({...entry,visibility:'public'})})).json();assert.ok(created.entry.id);const changed={...entry,id:created.entry.id,version:1};assert.equal((await call('entries',env,{method:'POST',headers,body:JSON.stringify(changed)})).status,200);assert.equal((await call('entries',env,{method:'POST',headers,body:JSON.stringify(changed)})).status,409);assert.equal((await (await call('public?kind=blog&locale=tw',env)).json()).entries.length,0);assert.equal((await call('auth/logout',env,{method:'POST',headers})).status,200);assert.equal((await call('entries',env,{headers})).status,401);});
test('match metrics reject impossible data and do not claim replay analysis',()=>{const match={...entry,kind:'match',meta:{hero:'A',mode:'ranked',rank:'x',result:'win',evidence:'',minutes:20,kills:4,deaths:0,assists:5,teamKills:10}};const m=normalize(match).meta;assert.match(analysis(m).en.join(' '),/No replay was analyzed/);assert.match(analysis(m).en.join(' '),/90%/);assert.throws(()=>normalize({...match,meta:{...m,teamKills:3}}));assert.throws(()=>normalize({...entry,visibility:'PUBLIC'}));});
test('Apple verifies signature, owner, audience, expiry and nonce',async()=>{const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const pub=await crypto.subtle.exportKey('jwk',keys.publicKey);pub.kid='test';pub.alg='RS256';const enc=new TextEncoder();const make=async p=>{const s=b64(enc.encode(JSON.stringify({alg:'RS256',kid:'test'})))+'.'+b64(enc.encode(JSON.stringify(p)));return s+'.'+b64(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,enc.encode(s)));};const p={iss:'https://appleid.apple.com',aud:'client',sub:'owner',nonce:'nonce',iat:now(),exp:now()+60},env={APPLE_CLIENT_ID:'client',APPLE_OWNER_SUB:'owner'};assert.equal((await verifyAppleToken(await make(p),env,'nonce',[pub])).sub,'owner');for(const bad of [{sub:'stranger'},{aud:'evil'},{exp:now()-1},{nonce:'wrong'}])await assert.rejects(()=>make({...p,...bad}).then(t=>verifyAppleToken(t,env,'nonce',[pub])));const t=await make(p);await assert.rejects(()=>verifyAppleToken(t.slice(0,-10)+'AAAAAAAAAA',env,'nonce',[pub]));});
test('Notion full snapshot removes unpublished/archived copies; failed fetch preserves records',async()=>{const DB=db(),env={DB,NOTION_TOKEN:'secret',NOTION_DATA_SOURCE_ID:'source'};await DB.prepare("INSERT INTO entries(id,kind,locale,slug,title,body,visibility,source,updated_at) VALUES('old','blog','tw','old','old','text','public','notion','today')").bind().run();const old=globalThis.fetch;try{globalThis.fetch=async()=>new Response('',{status:503});await assert.rejects(()=>syncNotion(env));assert.equal((await DB.prepare('SELECT * FROM entries').all()).results.length,1);globalThis.fetch=async()=>Response.json({results:[],has_more:false});assert.equal(await syncNotion(env),0);assert.equal((await DB.prepare('SELECT * FROM entries').all()).results.length,0);}finally{globalThis.fetch=old;}});
test('appearance writes require owner session and reject arbitrary CSS',async()=>{const DB=db(),env=full(DB),token='appearance-token';await DB.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await hash(token),'owner','csrf',now()+100).run();const headers={Cookie:'__Host-studio='+token,Origin:env.ADMIN_ORIGIN,'X-CSRF-Token':'csrf'};const data={theme:'night',accent:'#d1a485',motion:false,sound:true,hero:{tw:'暮色',en:'Dusk',jp:'夕暮れ'}};assert.equal((await call('appearance',env,{method:'POST',body:JSON.stringify(data)})).status,401);assert.equal((await call('appearance',env,{method:'POST',headers,body:JSON.stringify({...data,accent:'url(https://evil.test)'})})).status,400);assert.equal((await call('appearance',env,{method:'POST',headers,body:JSON.stringify(data)})).status,200);assert.deepEqual(await(await call('appearance',env)).json(),data);});
