import {normalize} from './core.mjs';
export async function syncNotion(env){
 if(!env.DB||!env.NOTION_TOKEN||!env.NOTION_DATA_SOURCE_ID)throw new Error('notion unconfigured');
 const lease=String(Date.now()+600000);const lock=await env.DB.prepare("INSERT INTO sync_state(name,value) VALUES('notion-lock',?) ON CONFLICT(name) DO UPDATE SET value=excluded.value WHERE CAST(sync_state.value AS INTEGER)<? RETURNING value").bind(lease,Date.now()).first();if(!lock)throw new Error('sync in progress');
 try{let cursor,rows=[];do{const r=await fetch(`https://api.notion.com/v1/data_sources/${encodeURIComponent(env.NOTION_DATA_SOURCE_ID)}/query`,{method:'POST',headers:{Authorization:`Bearer ${env.NOTION_TOKEN}`,'Notion-Version':'2025-09-03','Content-Type':'application/json'},body:JSON.stringify({page_size:100,...(cursor?{start_cursor:cursor}:{})}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('notion query failed');const d=await r.json();if(!Array.isArray(d.results))throw new Error('invalid notion response');rows.push(...d.results);if(rows.length>500)throw new Error('sync size exceeds 500; pagination worker needed');cursor=d.has_more?d.next_cursor:null;if(d.has_more&&!cursor)throw new Error('missing cursor');}while(cursor);
 const plain=p=>(p?.rich_text||p?.title||[]).map(x=>x.plain_text??x.text?.content??'').join('');
 const entries=rows.filter(r=>!r.archived&&!r.in_trash).map(r=>{const p=r.properties;let meta={};const kind=p.Kind?.select?.name;if(kind==='match'){for(const k of ['hero','mode','rank','evidence'])meta[k]=plain(p[k]);meta.result=p.result?.select?.name;for(const k of ['minutes','kills','deaths','assists','teamKills'])meta[k]=p[k]?.number??null;}return {id:'notion-'+r.id,...normalize({kind,locale:p.Locale?.select?.name,slug:plain(p.Slug),title:plain(p.Name),body:plain(p.Body),visibility:p.Publish?.checkbox===true&&p.Visibility?.select?.name==='public'?'public':'private',meta})};});
 // Full snapshot is validated before one transactional batch. Unpublishing and
 // archiving remove the previously public copy on the next successful sync.
 const statements=[env.DB.prepare("DELETE FROM entries WHERE source='notion'")];for(const x of entries)statements.push(env.DB.prepare("INSERT INTO entries(id,kind,locale,slug,title,body,visibility,meta,source,version,updated_at) VALUES(?,?,?,?,?,?,?,?,'notion',1,?)").bind(x.id,x.kind,x.locale,x.slug,x.title,x.body,x.visibility,JSON.stringify(x.meta),new Date().toISOString()));statements.push(env.DB.prepare("INSERT INTO sync_state(name,value) VALUES('notion-last-sync',?) ON CONFLICT(name) DO UPDATE SET value=excluded.value").bind(new Date().toISOString()));await env.DB.batch(statements);return entries.length;
 }finally{await env.DB.prepare("DELETE FROM sync_state WHERE name='notion-lock' AND value=?").bind(lease).run();}
}
